/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated.assistant'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated.career'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated.expenses'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated.goals'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated.health'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated.interview'
import { Route as AuthenticatedPlacementsRouteImport } from './routes/_authenticated.placements'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated.resume'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated.roadmap'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated.study'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated.assistant.index'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated.assistant.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlacementsRoute = AuthenticatedPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/career': typeof AuthenticatedCareerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/placements': typeof AuthenticatedPlacementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/study': typeof AuthenticatedStudyRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/placements': typeof AuthenticatedPlacementsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/career'
    | '/dashboard'
    | '/expenses'
    | '/goals'
    | '/health'
    | '/interview'
    | '/placements'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/study'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/career'
    | '/dashboard'
    | '/expenses'
    | '/goals'
    | '/health'
    | '/interview'
    | '/placements'
    | '/profile'
    | '/resume'
    | '/roadmap'
    | '/study'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/assistant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/assistant'
    | '/_authenticated/career'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/goals'
    | '/_authenticated/health'
    | '/_authenticated/interview'
    | '/_authenticated/placements'
    | '/_authenticated/profile'
    | '/_authenticated/resume'
    | '/_authenticated/roadmap'
    | '/_authenticated/study'
    | '/api/chat'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/placements': {
      id: '/_authenticated/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AuthenticatedPlacementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
  }
}

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedPlacementsRoute: typeof AuthenticatedPlacementsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedPlacementsRoute: AuthenticatedPlacementsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
